name: flutter_events
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.4.0 <3.0.0"

dependencies:
  toast: ^0.1.5
  esys_flutter_share: ^1.0.2
  qr_flutter: ^3.1.0
  localstorage: ^3.0.0
  http: ^0.12.0+2
  font_awesome_flutter: ^8.2.0
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_launcher_icons: "^0.7.3"
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico/Pacifico-Regular.ttf
  assets:
    - images/picture.png
    - images/ticket.png

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/logo.jpeg"
